import os
from typing import TypedDict, List, Annotated

from langgraph.graph.message import add_messages
from langchain_core.documents import Document

from src.core.db import get_vector_store


# ── State ──────────────────────────────────────────────────────────────────────
# The state is the shared data that flows through the entire graph.
# Each node reads from state and returns updated state.
#
# New fields added for the NL2SQL (product) routing path:
#   route        — set by router_node: "product" | "document"
#   generated_sql — the SQL generated by the NL2SQL node
#   sql_result   — raw string output returned by executing the SQL

class RAGState(TypedDict):
    query: str
    hyde_query: str
    use_hyde: bool
    retrieved_docs: List[Document]   # Output of Node 1 — wide retrieval (k=10)
    reranked_docs: List[Document]    # Output of Node 2 — narrowed by reranker (top_n=3)
    response: dict                   # Output of Node 3 — final structured answer
    retries: int
    messages: Annotated[List, add_messages]
    route: str                       # "product" or "document" or "hybrid" — set by router_node
    generated_sql: str               # SQL generated by nl2sql_node
    sql_result: str                  # Raw SQL execution result
    hybrid_sql_response: dict
   
